# Use the official Python 3.11 image
FROM langchain-projects-base

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Command to run when the container starts
CMD ["python", "./prompt.py"]